### ISSUE TITLE
Downgrade dependencies

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [phparkitect/arkitect#107]
I think it could be useful to downgrade our dependencies to the version that can support PHP 7.1  and support Symfony projects that are using a version minor than Symfony 4.4  (example Symfony 3.4)

**Comment by pfazzi** [comment]
My 2 cents: this example IMHO confirms how important it is to find an alternative way to install the tool.

PS: If we downgrade we still have to support later versions as well, and if for instance Symfony Console version 6 will not be backwards compatible, the game will no longer work.

**Comment by AlessandroMinoccheri** [comment]
I agree with you @pfazzi we need to find a good strategy for install the tool.

**Comment by AlessandroMinoccheri** [comment]
Closed by #110
