### ISSUE TITLE
Analyze deptrac rules to compare with ours behavior

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [phparkitect/arkitect#150]

**Comment by AlessandroMinoccheri** [comment]
@micheleorselli 
If I have understood well, deptrac gets only directories declared as layers.
So, for this reason, it doesn't consider vendor libraries.

See the answer to this issue here:
https://github.com/qossmic/deptrac/issues/231

**Comment by micheleorselli** [comment]
oh, that's clever :-) 
Do you think we should change the current arkitect's behaviour ?

**Comment by AlessandroMinoccheri** [comment]
Yes, it's a different approach.
IMHO it could be a future step, at the moment I can see some features for example:
we can add the possibility to add/remove vendor dependencies with a method like: `excludeVendors()` `includeVendors`

What do you think @micheleorselli ?
