### ISSUE TITLE
excludeVendors feature

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [phparkitect/arkitect#151]
@fain182 @micheleorselli 
what do you think about adding a new feature `excludeVendors`?
It could be useful to create some rule for example:
If I want to check that a namespace depends only on itself, you need to add all vendors to the dependency admitted. 
Example:

```
return static function (Config $config): void {
    $mvc_class_set = ClassSet::fromDir(__DIR__.'/src/');

    $rule_1 = Rule::allClasses()
        ->that(new ResideInOneOfTheseNamespaces('Investments\*'))
        ->should(new DependsOnlyOnTheseNamespaces('Investments', 'Symfony', 'Doctrine'))
        ->because('we want to avoid interdependency');

    $config
        ->add($mvc_class_set, ...[$rule_1]);
};

```

With this new feature, you can avoid it, for example:

```
return static function (Config $config): void {
    $mvc_class_set = ClassSet::fromDir(__DIR__.'/src/');

    $rule_1 = Rule::allClasses()
        ->that(new ResideInOneOfTheseNamespaces('Investments\*'))
        ->should(new DependsOnlyOnTheseNamespaces('Investments'))
        ->excludeVendors()
        ->because('we want to avoid interdependency');

    $config
        ->add($mvc_class_set, ...[$rule_1]);
};

```

What do you think?

**Comment by fain182** [comment]
I am not sure that "exclude vendors" should be at the same level of `that`, `should`, 'because`... unless it has a meaning for all the rules. 

And i suggest to compose an english sentence to make the API sound good..
```
All classes
that reside in one of these namespaces: Investments
should depend only on on these **internal namespaces**: Investments
because we want to avoid interdependency
```
It could work? another rule that exclude the vendors? or maybe the default rule exclude the vendors (that I think will be the most used) and we make a custom one to include the vendors?

**Comment by AlessandroMinoccheri** [comment]
Sorry for the delay in this answer @fain182 
Excluding vendors by default sounds good but I am thinking about the scenario:
`I want to be sure that inside my domain there isn't libraries or other things except for a specific library`
This is an edge case maybe.

We can exclude vendors by default, but the problem is that you need to implement something to enable vendors whenever you want.

What do you think?

**Comment by fain182** [comment]
It's a real scenario or just imagination? Why do you want that?

**Comment by AlessandroMinoccheri** [comment]
Example:
I would like that my domain folder doesn't contain external dependencies except for `Ramsey/UUid`. This could be a real scenario.

**Comment by zerai** [comment]
From  dependencies point of view  domain purity is rare, even in good codebase external 'vendors lib' in domain are allowed/accepted.

Very common cases | real scenario:

1 only ramsey/uuid  
2 ramsey/uuid + assertion lib (beberlei | webmozart)
3 ramsey/uuid + assertion lib (beberlei | webmozart) + collections lib (doctrine/collections)

**Comment by AlessandroMinoccheri** [comment]
Yes, I agree with @zerai and I would like to know how do you expect to explicit this rule? 
Example:

```
All classes
that reside in one of these namespaces: Investments
should depend only on these **internal namespaces**: Investments excepted for this namespace foo/bar and xxx/xyz
because we want to avoid interdependency
```

**Comment by fain182** [comment]
I thought a little about it, but this should be already working on our code :top: 

```php
Rule::allClasses()
        ->that(new ResideInOneOfTheseNamespaces('Investments\*'))
        ->should(new DependsOnlyOnTheseNamespaces('Investments', 'foo/bar', 'xxx/xyz'))
        ->because('we want to avoid interdependency');
```

**Comment by AlessandroMinoccheri** [comment]
It can work, I thought about it too.
In my opinion, we can improve the documentation to explain this example. 
What do you think?
We can also create a specific doc for some examples of usage.
@fain182

**Comment by fain182** [comment]
Yes, a page with a lot of common examples could be really useful!

**Comment by AlessandroMinoccheri** [comment]
I close this issue because we will add examples about this context.
