### ISSUE TITLE
Crashes with PHP 7.4 syntax

### ISSUE THREAD

**Issue by davidstoker** [phparkitect/arkitect#160]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Library Version | 0.1.14
| PHP version     | 7.4.23

#### Summary

Current PHP-Parser configuration in this project causes crashes within `php-parser` using newer syntax introduced in 7.4.

#### Current behavior

I was trying this out on a large project that runs PHP 7.4. When running an initial check, many crashes dumped out from `php-parser` with `Parse Error: Syntax error, unexpected T_STRING, expecting T_PAAMAYIM_NEKUDOTAYIM on line X`.

The places referenced utilize Arrow functions which were introduced in PHP 7.4.

`FileParser` in this project configures an `Emulative` from `php-parser` with a `phpVersion` of 7.1

https://github.com/phparkitect/arkitect/blob/911bf96da29ae095069680771070f8d36c244e63/src/Analyzer/FileParser.php#L13-L30

The `Emulative` options say `phpVersion` sets the version to emulate which means this is forcing emulation of 7.1? Is this intentional? Commenting out that option that's passed to `Emulative` allows the checks to run correctly on my project.

https://github.com/nikic/PHP-Parser/blob/0a20979a62bc159fa0159ec7a4b5e2360bfa1abc/lib/PhpParser/Lexer/Emulative.php#L38-L40

#### How to reproduce

Try running checks on a file using PHP 7.4+ on a file with an arrow function like `$fn1 = fn($x) => $x + $y;` in it.

#### Expected behavior

Checks would execute without crashing.

**Comment by AlessandroMinoccheri** [comment]
Thanks, @davidstoker for this issue, I am working to fix it in this PR: #161

**Comment by 4n70w4** [comment]
May be similar issue:

```
Parse Error: Syntax error, unexpected T_VARIABLE, expecting ':' on line 193#0 phar:///var/www/promo/phparkitect.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(159): PhpParser\ParserAbstract->doParse()
```

```
Parse Error: Syntax error, unexpected T_DOUBLE_ARROW, expecting ')' on line 325#0 phar:///var/www/promo/phparkitect.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(159): PhpParser\ParserAbstract->doParse()
```

```
Parse Error: Syntax error, unexpected T_VARIABLE, expecting ':' on line 951#0 phar:///var/www/promo/phparkitect.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(159): PhpParser\ParserAbstract->doParse()
```

```
Parse Error: Call to undefined method PhpParser\Node\Expr\PropertyFetch::toString()#0 phar:///var/www/promo/phparkitect.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): Arkitect\Analyzer\FileVisitor->enterNode(Object(PhpParser\Node\Expr\New_))
```

**Comment by AlessandroMinoccheri** [comment]
@4n70w4 yes, when we will release the next version we can check it.
Thanks @4n70w4

**Comment by AlessandroMinoccheri** [comment]
Hi @davidstoker we have released version 0.1.15 to solve the problem of this issue.
Thanks, let me know.

**Comment by 4n70w4** [comment]
New error:

`
Parse Error: Call to undefined method PhpParser\Node\Expr\PropertyFetch::toString()#0 phar:///var/www/promo/phparkitect.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): Arkitect\Analyzer\FileVisitor->enterNode(Object(PhpParser\Node\Expr\New_))
`

`
  ____  _   _ ____   _         _    _ _            _
 |  _ \| | | |  _ \ / \   _ __| | _(_) |_ ___  ___| |_
 | |_) | |_| | |_) / _ \ | '__| |/ / | __/ _ \/ __| __|
 |  __/|  _  |  __/ ___ \| |  |   <| | ||  __/ (__| |_
 |_|   |_| |_|_| /_/   \_\_|  |_|\_\_|\__\___|\___|\__|

PHPArkitect version 0.1.15
`

**Comment by AlessandroMinoccheri** [comment]
Hi @4n70w4 can you try to launch the tool with `-v` option to see the full error?

**Comment by davidstoker** [comment]
@AlessandroMinoccheri Works perfect now on my project. Thank you for fixing!

**Comment by AlessandroMinoccheri** [comment]
Thanks to you @davidstoker 👍

**Comment by AlessandroMinoccheri** [comment]
@4n70w4 I close this issue and I have opened a new one for your problem:
#168 
Let me know if you can add more information about the issue to reproduce it and fix it.
