### ISSUE TITLE
Extend() should implement Expression instead of extending from Expresssions

### ISSUE THREAD

**Issue by benr77** [phparkitect/arkitect#163]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Library Version | 0.1.15
| PHP version     | 8.0.8

#### Summary

Looking at the `Arkitect\Expression\ForClasses\Implement` and `\Arkitect\Expression\ForClasses\Extend` classes, it would seem that the `Extend` class should have a declaration of

`class Extend implements Expression`

instead of currently

`class Extend extends Expressions`

I have tried this and the analysis still runs fine. (however, I'm still getting a weird result as per my other issue reported in #162 which may or may not be related).

Thanks

**Comment by micheleorselli** [comment]
You are very right sir, that was a mistake, fix is coming soon 🙇
