### ISSUE TITLE
Improve output readability (with colors?)

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [phparkitect/arkitect#176]
I think that it could be useful to add colors to our output to help developers when they launch the tool.

**Comment by mloru** [comment]
It could be useful also if the tool would display a message when no violations has been detected.

**Comment by mloru** [comment]
Hi! I've recently updated my phparkitect fork to [confirm that no violations have been detected with a message](https://github.com/mloru/arkitect/pull/2)
If you think this could be useful, it can be merged on the upstream repo too.

**Comment by AlessandroMinoccheri** [comment]
Hi @mloru , you can try to open a new pull request into this repository and we will review it.
