### ISSUE TITLE
Using wildcards in namespaces (ResideInOneOfTheseNamespaces)

### ISSUE THREAD

**Issue by ricfio** [phparkitect/arkitect#186]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Library Version | 0.2.2
| PHP version     | 8.0.12

#### Summary

Using wildcards in the namespaces of `ResideInOneOfTheseNamespaces` constructor the matching namespaces are not selected.

#### Current behavior

The pattern `*\Vegetables` do not select classes in the namespace `Food\Vegetables` such as `Food\Vegetables\Carrot`.

See for example this configuration:
```
Rule::allClasses()
    ->that(new ResideInOneOfTheseNamespaces('*\Vegetables'))
```

#### How to reproduce

I have add some input to `shouldMatchNamespacesProvider` that fail the test `ResideInOneOfTheseNamespacesTest` here:
https://github.com/ricfio/arkitect/tree/wildcard-in-namespace

#### Expected behavior

Test should be pass

#### Note
If you confirm me that it is a bug, I could try to fix it myself

**Comment by ricfio** [comment]
Fixed by PR https://github.com/phparkitect/arkitect/pull/188

**Comment by AlessandroMinoccheri** [comment]
Hi @ricfio In my opinion if you declare: `*\Vegetables` I'm not expecting that `Food\Vegetables\Carrot` to be taken.

If you would check  `Food\Vegetables\Carrot` too, you need to add another wild card at the end like this: `*\Vegetables\*`.

What do you think?

**Comment by AlessandroMinoccheri** [comment]
Thanks @ricfio
