### ISSUE TITLE
check report sorted by the folder-first strategy

### ISSUE THREAD

**Issue by ricfio** [phparkitect/arkitect#202]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

I would like that the check report will be alphabetic sorted by the folder-first strategy.

For example this output (alphabetic sorted):
```
App\Domain\Assert violates rules
  ...
App\Domain\Asset\Asset violates rules
  ...
App\Domain\Asset\AssetCollection violates rules
  ...
App\Domain\Bank\BankBalance violates rules
  ...
App\Domain\Bank\BankOperation violates rules
  ...
App\Domain\Collection violates rules
  ...
```

should be sorted by the folder-first strategy as follow:
```
App\Domain\Asset\Asset violates rules
  ...
App\Domain\Asset\AssetCollection violates rules
  ...
App\Domain\Bank\BankBalance violates rules
  ...
App\Domain\Bank\BankOperation violates rules
  ...
  ...
App\Domain\Assert violates rules
  ...
App\Domain\Collection violates rules
  ...
```

**Comment by fain182** [comment]
Interesting, in which situation you found that this was useful to you? :slightly_smiling_face:

**Comment by ricfio** [comment]
... when I compare the check report with my project folders and files that are sorted differently
