### ISSUE TITLE
The violation error message doesn't perfectly match the rule class name

### ISSUE THREAD

**Issue by ricfio** [phparkitect/arkitect#208]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

The violation error message doesn't perfectly match the rule class name

Example:
'should not depend on classes outside in namespace' vs NotHaveDependencyOutsideNamespace(...)

I think it would be better to print:
'not have dependency outside namespace'

**Comment by AlessandroMinoccheri** [comment]
Fixed by #211 

Thanks!
