### ISSUE TITLE
How can certain classes be excluded from Dependency checks

### ISSUE THREAD

**Issue by benr77** [phparkitect/arkitect#215]
|    Q            |   A
|---------------- | ------
| Library version | 0.2.7
| PHP version     | 8.1

### Support Question

I have a check for my domain model purity:

```
$domainLayerIsolation = Rule::allClasses()
        ->that(new ResideInOneOfTheseNamespaces('App\AppointmentMgmt\Domain'))
        ->should(new NotHaveDependencyOutsideNamespace('App\AppointmentMgmt\Domain'))
        ->because('we want protect our domain');
```
This generates lots of violations about certain classes that are from different namespaces, which I have allowed in the domain layer.

Is there a way to exclude certain classes - the domain model does have certain dependencies that I'd like to permit without them raising violations.

Thanks

**Comment by AlessandroMinoccheri** [comment]
Hi @benr77 we are discussing this feature many times like in this issue: #200 and at the moment you can use  a trick, instead of using this:

```
->should(new NotHaveDependencyOutsideNamespace('App\AppointmentMgmt\Domain'))
```

You can. use this:

```
->should(new DependsOnlyOnTheseNamespaces('App\AppointmentMgmt\Domain', 'OtherNamespace\'))
```

If you want to help with the new feature about excluding some dependencies, feel free to open a PR.

**Comment by benr77** [comment]
Thank you for pointing out #200 - the title of that issue is not very descriptive as you are really talking about how to exclude classes in a generic way, not just for \Exceptions.

I will try your workaround - looks like it will work well for me. Thanks again!

**Comment by benr77** [comment]
I have just discovered that `ResideInOneOfTheseNamespaces` is not picking up any classes at all... It was working on older releases, but on 0.2.7 it seems not.

```
->that(new ResideInOneOfTheseNamespaces('App\AppointmentMgmt\Domain'))
```

**Comment by AlessandroMinoccheri** [comment]
@benr77 I am trying without problems with the newer version of the expression `ResideInOneOfTheseNamespaces `.

If you have a new problem, can you please open a new PR with a concrete example to understand well the problem?

**Comment by benr77** [comment]
My apologies. I had my `src` directory set incorrectly. `ResideInOneOfTheseNamespaces` is working correctly. Sorry for the confusion.

**Comment by AlessandroMinoccheri** [comment]
No problem @benr77 
Thanks for your contribution!
