### ISSUE TITLE
Why do not merge allClasses() with that(...)?

### ISSUE THREAD

**Issue by ricfio** [phparkitect/arkitect#218]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | yes

#### Summary

Why do not merge the concepts `Rule::allClasses()` with `->that(...)` ?

I think it is more direct write anything as:
`Rule::allClasses(new ResideInOneOfTheseNamespaces('App\HappyIsland'))`
or if you prefer:
`Rule::allClassesThat(new ResideInOneOfTheseNamespaces('App\HappyIsland'))`

instead of

`Rule::allClasses()->that(new ResideInOneOfTheseNamespaces('App\HappyIsland'))`

What would be the pros and cons?

**Comment by micheleorselli** [comment]
I prefer the former version, slightly more verbose but more readable
