### ISSUE TITLE
add violations count

### ISSUE THREAD

**Issue by ricfio** [phparkitect/arkitect#224]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Could a violations count be added in the phparkitect output?
It seems to me that at the moment it is not there.

**Comment by micheleorselli** [comment]
that's probably a good addition, makes sense to me

**Comment by AlessandroMinoccheri** [comment]
@ricfio, do you want to try to add this feature?

**Comment by ricfio** [comment]
sure, it's very simple.
see https://github.com/phparkitect/arkitect/pull/235

**Comment by AlessandroMinoccheri** [comment]
closed by #237
