### ISSUE TITLE
Ignore Syntax errors argument

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [phparkitect/arkitect#231]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

It could be useful to add an argument to specify that all syntax errors (parsed errors) should be ignored because sometimes we can have situations where we want to check only rules, not the syntax.

**Comment by micheleorselli** [comment]
I have mixed feelings about this: for sure it could be useful to have such thing but I am afraid it will open a can of worms. The question in my mind is: **do we really want to apply architectural rules to a codebase which contains syntax errors**? It is like deciding on the curtains' color when you have an hole in the wall :-). 

Parsing a codebase with syntax error could also lead to unexpected results: missing class or dependencies or stuff like that. 

If we want to go down this way then we should make really explicit that some files could not be parsed and for that reason the result of the analysis may be inaccurate. What do you think?

**Comment by AlessandroMinoccheri** [comment]
Uhm I agree with you, I think that for now, it's better to avoid this behavior. 
I close this issue and the relative PR, if someday we need it we can reopen it.
