### ISSUE TITLE
phparkitect.phar does not work on PHP 7.3

### ISSUE THREAD

**Issue by LuigiCardamone** [phparkitect/arkitect#242]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | yes/no
| Library Version | 0.2.15
| PHP version     | 7.3.33

#### Summary

phparkitect.phar does not work on PHP 7.3

#### Current behavior

I get this error:
```
Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.3.33-1+ubuntu18.04.1+deb.sury.org+1.

PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.3.33-1+ubuntu18.04.1+deb.sury.org+1. in phar:///var/www/app/phparkitect.phar/vendor/composer/platform_check.php on line 24
```

#### How to reproduce

On Ubuntu 18 with PHP 7.3 the error appears following the basic setup instructions:
```
wget https://github.com/phparkitect/arkitect/releases/latest/download/phparkitect.phar
chmod +x phparkitect.phar
./phparkitect.phar check

```

Any idea?
(I know that PHP 7.3 is in EOL, but it is not up on me :-) )

**Comment by AlessandroMinoccheri** [comment]
Hi @LuigiCardamone 
I am not sure if it can work or not, but can you try to specify the target PHP version In this way?

```
./phparkitect.phar check --target-php-version=7.3
```

Let me know.

**Comment by pfazzi** [comment]
Ciao @LuigiCardamone :)

**Comment by LuigiCardamone** [comment]
Hi @AlessandroMinoccheri, nope, same error.
I will try in a project with PHP 7.4, thanks anyway.

@pfazzi Ciao! Congratulations for this very interesting project!

**Comment by AlessandroMinoccheri** [comment]
@LuigiCardamone can you install it via `composer`?

**Comment by LuigiCardamone** [comment]
Unfortunately no: several dependencies conflicts on our main (and huge) project. I will try on a test project

**Comment by AlessandroMinoccheri** [comment]
@LuigiCardamone, have you tried phparkitect in a project with PHP 7.4?
Can you also share more information about your problem with the PHP7.3 project? For example composer constraints or something relevant to reproduce the problem.

**Comment by pfazzi** [comment]
We could try to reproduce the issue with a docker container, what do you think guys?

**Comment by AlessandroMinoccheri** [comment]
Yes, it's important to reproduce a similar error so with the right constraints.

**Comment by LuigiCardamone** [comment]
@AlessandroMinoccheri with PHP 7.4 everything works fine.

My conflicts with composer and PHP 7.3 are not important since such conflicts will be different on each project. In my case, the first conflict was about `webmozart/assert`, but after that many others appeared. However we will upgrade to PHP 8 in a month or two.

It would be interesting to understand why `phparkitect.phar` does not work on PHP 7.3

**Comment by micheleorselli** [comment]
This #246 should fix it

**Comment by LuigiCardamone** [comment]
Where I can find the `phparkitect.phar` for release 0.2.18?
Here https://github.com/phparkitect/arkitect/releases latest release is 0.2.16

**Comment by micheleorselli** [comment]
@LuigiCardamone nom nom nom, Phar creation is still broken on GA 😭 ... let me check again. In the meantime would you mind trying this version? [phparkitect.phar.gz](https://github.com/phparkitect/arkitect/files/8233342/phparkitect.phar.gz). Just remove the .gz extension

**Comment by LuigiCardamone** [comment]
@micheleorselli, it works like a charm! Thank you!
