### ISSUE TITLE
how to use `because()`?

### ISSUE THREAD

**Issue by hgraca** [phparkitect/arkitect#258]
|    Q            |   A
|---------------- | ------
| Library version | 0.2.18
| PHP version     | 7.2

### Support Question

Hi, I'm trying to figure out how to show the `because()` when rules fail, but I cant figure out how.

So, when we have a rule like 

```php
$rule_1 = Rule::allClasses()
        ->that(new ResideInOneOfTheseNamespaces('App\Infrastructure\Controller'))
        ->should(new HaveNameMatching('*Controller'))
        ->because('we want to uniform controller name.');
```
When this rule fails, the error is 

`should have a name that matches *Controller`

but it would be great if it would show 

`should have a name that matches *Controller because we want to uniform controller name.`.

This would be helpful to explain to others what is the reasoning behind the rule.

**Comment by AlessandroMinoccheri** [comment]
Hi @hgraca at the moment the `because` is used only when you write the rule to specify why you added it.
But I think it can be helpful also in the error message.

Do you want to try to create a PR to solve the problem?

**Comment by hgraca** [comment]
This is awesome ppl!!!
I'm sorry, I missed your first message.

Thanks a lot, and keep it up!

I have created a few rules for the project I'm working on, I will submit MRs.

**Comment by AlessandroMinoccheri** [comment]
Thanks to you @hgraca :)
