### ISSUE TITLE
Class constant references erroneously flagged as uses of symbol outside namespace

### ISSUE THREAD

**Issue by azambon** [phparkitect/arkitect#272]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Library Version | 0.2.25
| PHP version     | 8.1.8

#### Summary

When upgrading from 0.2.24 to 0.2.25 we began receiving notifications of namespace violation errors when a class constant is used within the class itself. This includes "self::class" and "static::class" constants.

#### How to reproduce

Consider this sample class:

```
namespace Foo;

class A
{
    const C = 'test';

    public function f(): string
    {
        return self::C;
    }

    public function g(): string
    {
        return self::class;
    }

    public function h(): string
    {
        return static::class;
    }
}
```

And this validation rule:

```
Rule::allClasses()
    ->that(new ResideInOneOfTheseNamespaces('Foo'))
    ->should(
        new NotHaveDependencyOutsideNamespace('Foo')
    );
```

#### Expected behavior

The above code should not produce any violation with the specified validation rules, as no symbol outside namespace Foo is ever referenced.

#### Current behavior

The validation reports an error on the lines that reference the C, self::class and static::class constants, saying that a symbol outside the namespace is used.

**Comment by AlessandroMinoccheri** [comment]
Hi @azambon we should fix it with the new version `0.2.26`
Feel free to write again if you have other problems!

Thanks for your contribution!

**Comment by azambon** [comment]
Thank you very much, I'll let you know as soon as our automated tools recheck everything with the new version if there's any other issue.

I wish all package maintainers were as quick in responding to issues as you have been :+1:

**Comment by azambon** [comment]
Yep, confirmed, all good with the new version.
Thank you again

**Comment by AlessandroMinoccheri** [comment]
Perfect, Thanks to you @azambon
