### ISSUE TITLE
Remove redundancy from config file name (use `arkitect.php`)

### ISSUE THREAD

**Issue by Wirone** [phparkitect/arkitect#286]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | yes
| BC Break    | it depends (backward compatibility may be provided)

#### Summary

I would like to propose slight change in this nice-looking tool: use `arkitect.php` instead of `phparkitect.php` as config file.

I know that tool's full name is PHPArkitect, but in my opinion it looks like redundancy to have PHP in the config file's name twice (once as an extension, but still). The other tools with PHP prefix (CS Fixer, Code Sniffer, PHPStan, PHPUnit) use prefix in config file's name, but those tools use YAML, XML or NEON formats, hence no redundancy there. On the other hand ECS and Rector have PHP config files but no `PHP` in the name 😉 

I will understand if you reject this proposal, but I think it can be at least discussed 🙂 

PS. Today I discovered Arkitect and I am going to give it a try soon! Thank you 🍻

**Comment by AlessandroMinoccheri** [comment]
Thanks @Wirone for your contribution!
You are right about the redundancy.
I think also that using the same name `phparkitect.php` for the config file, and `phparkitect` for the CLI, can help developers to remember the command.
This is a good discussion for me to improve the experience for us as developers so I am open to changing things if we can improve something.

**Comment by Wirone** [comment]
Personally I define Composer scripts and/or `Makefile` targets that wrap original command execution (and many people I know do it too). So most probably I will use `composer arkitect` (less typing, the better 😉). 

Maybe it would be good idea to just support both files and let people decide which one they want to use 🤔?

PS. Like in other tools, it would be good to have support for `*.dist` file, that would be searched as fallback when `*.php` file is not present. It would allow defining default config that could be overridden locally. But it's probably topic for other issue 😉

**Comment by fain182** [comment]
Even if I understand that the redundancy in the name `phparkitect.php` is not beautiful, I think consistency is the key here.
We want to surprise the user the least possible to make this tool delightful to use.
And Arkitect is a too common name, so we need to prepend "php" everywhere to make it recognizable.

If you prefer to use a different filename anyway you can with the `--config` option :slightly_smiling_face: 
`phparkitect check --config=arkitect.php`
