### ISSUE TITLE
Improve developer experience with a CLI command to test selectors (glob)

### ISSUE THREAD

**Issue by xthiago** [phparkitect/arkitect#290]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

It would be very nice to have a CLI command to quickly test selectors like that:

```bash
# simple version - only shows matches:
$ phparkitect selector:test namespace *Controller
Matches:
App/Controller/UserController.php
App/Controller/CustomerController.php

# robust version that shows everything 
$ phparkitect selector:test namespace *Controller --show-all
Matches | File
❌      | App/Entity/User.php
✔️      | App/Controller/UserController.php
✔️      | App/Controller/CustomerController.php
❌      | App/Repository/UserRepository.php
```

Inspiration came from Symfony:

 - [Debug @ Symfony Router](https://symfony.com/doc/6.1/routing.html#debugging-routes):
   - `bin/console debug:router name-of-router`
   - `bin/console router:match /a/nice/path`
 - [Debug @ Symfony Service Container](https://symfony.com/doc/6.1/service_container/debug.html)
   - `bin/console debug:container App\Service\Mailer`

**Comment by AlessandroMinoccheri** [comment]
Hi @xthiago, thanks for this issue.
I like your idea! 
What do you think @fain182 @micheleorselli ?

**Comment by fain182** [comment]
Great idea!
Maybe I would use the complete name of the selector, so for example:
`phparkitect selector:test ResideInOneOfTheseNamespaces *Controller`

In this way we can develop it once for all the selectors, and without making learn any new keywords to the user.

**Comment by xthiago** [comment]
Yeah. It totally makes sense to me. :)
