### ISSUE TITLE
Attributes on enums are not processed by the `FileVisitor`

### ISSUE THREAD

**Issue by jerowork** [phparkitect/arkitect#306]
### Bug Report
|    Q            |   A
|---------------- | ------
| BC Break        | no
| Library Version | 0.2.32
| PHP version     | 8.1

#### Summary
While working in a project using `thecodingmachine/graphqlite` I wanted to guard with PHPArkitect if all GraphQL output types do have the attribute `Type`. While this does work as a charm for classes, it doesn't work for enums.

Investigating the codebase of PHPArkitect I found out that the `FileVisitor` does not retrieve the attributes for enums, likes it does for classes.

Background information: https://graphqlite.thecodingmachine.io/docs/type-mapping#enum-types

#### Current behavior
Running PHPArkitect for this enum:
```php
namespace Your\Namespace;

use TheCodingMachine\GraphQLite\Annotations\Type;

#[Type]
enum SomeEnum: string
{
    case SomeCase = 'some.case';
}
```

Results in a violation:
```
Your\Namespace\SomeEnum has 1 violations
  should have the attribute TheCodingMachine\GraphQLite\Annotations\Type because all GraphQL output types should be configured as GraphQLite Type
```

Configuration:
```php
use TheCodingMachine\GraphQLite\Annotations\Type;

return static function (Config $config): void {
    $classSet = ClassSet::fromDir(__DIR__.'/src');
    $config->add(
        $classSet,
        Rule::allClasses()
            ->that(new ResideInOneOfTheseNamespaces('Your\Namespace'))
            ->should(new HaveAttribute(Type::class))
            ->because('all GraphQL output types should be configured as GraphQLite Type'),
    );
};
```

#### How to reproduce
PR: https://github.com/phparkitect/arkitect/pull/305

#### Expected behavior
Just as with classes, PHPArkitect should handle attributes for enums as well, not resulting in a violation when attributes are present in the enum.

**Comment by AlessandroMinoccheri** [comment]
Closed By #305 
Thanks @jerowork
