### ISSUE TITLE
Is it possible not to depend on classes? 

### ISSUE THREAD

**Issue by nmeri17** [phparkitect/arkitect#318]
|    Q            |   A
|---------------- | ------
| Library version | x.y.z 
| PHP version     | x.y.z

### Support Question

I've gone through the documentation but can't find what I'm looking for. My intention is
1. Prevent class X from depending on a specific list of classes (from different namespaces, not one)
2. In fact, if it's possible to tailor permitted dependencies to a given list, that will be better
3. Set a list of classes allowed to depend on class Y

**Comment by nmeri17** [comment]
Thanks for the prompt response. It looks like it'll solve point #1. However, like I said, it'll be more preferable to solve #2. I wasn't aware the methods apply to classes (instead of just interfaces). If I use this expression, I believe DependsOnlyOnTheseNamespaces will help enforce presence of given classes by all who extend X. NotHaveDependencyOutsideNamespace would solves 3 ie restricting usage of Y to a given list

I'm assuming "dependence" here refers to constructors and methods. Two more questions:

1. Is there a way to distinguish between constructors and methods? I only want request objects on controller methods
2. Are there test handlers? I'd appreciate if I can retain the tests currently confirming this behaviour but connecting it to your library

**Comment by pfazzi** [comment]
> Is there a way to distinguish between constructors and methods? I only want request objects on controller methods 

ATM we don't distinguish between constructor dependencies and method dependencies, but it could be an nice new feature

> Are there programmatic handlers? 

Can you explain to me what you mean by programmatic handlers? What are those handlers intended to do?

**Comment by pfazzi** [comment]
Actually, we already have an integration with PHPUnit. Can this solve your problem?

**Comment by nmeri17** [comment]
> Are there programmatic handlers? I'd appreciate if I can retain the tests currently confirming this behaviour but connecting it to your library. I also want to call it from code 

By this, here's what I mean: my framework has a build step; it uses roadrunner under the hood. My first question is asking whether it's possible to invoke arkitect during this build process, so it can terminate if developer's code violates preset rules. Something like:

```php

try {
    Arkitect::processConfig($somePath);

    MyFramework::buildApp();
}
catch (ArkitectException)
```

I suppose I can equally test this from my end to confirm violations are duly reported. I wrote a component covering my dependency needs. The tests for it can hint at what I'm talking about. Please see https://github.com/nmeri17/suphle/blob/466378d36ba0b829707ea8d41fa2cd8dc5b974d4/tests/Integration/Services/Proxies/OnlyLoadedByTest.php#L16 . Now, I want to replace it with Arkitect since I can run this at build /compile phase as opposed to at runtime for each request. Do you understand

**Comment by AlessandroMinoccheri** [comment]
Hi @nmeri17 so if I understood well, you would like to use arkitect directly into the PHP code instead of using CLI, right?
At the moment I can see two ways:
* Launch the command using `exec` from the PHP code like: `exec('phparkitect check');`
* Using the code of `Arkitect\CLI\Command\Check.php` to run the tool, you need to run the Runner

**Comment by nmeri17** [comment]
@AlessandroMinoccheri the problem with using exec is that I can't catch errors or violation of the rules, and possibly prevent build of my own app OR report that test failed. I guess it can suffice to combine symfony Process with your Check command and the path to my rules configuration. If command returns Command::FAILURE, I can work with that status

Thanks for pitching in. If that's fine with you, it's OK to close the topic. I will write the config today or tomorrow and report here if it doesn't behave according to these discussions

**Comment by nmeri17** [comment]
Alright, I'm writing the config now. There's a rule I can't seem to locate. Suppose I want to limit classes that can depend on X, what combination of rules do I use? For instance, I only want Mail builders to be used by Task classes and not synchronous ones like the controller. I'm asking this so I don't assume and incorrectly test

**Comment by AlessandroMinoccheri** [comment]
I think that you can use `DependsOnlyOnTheseNamespaces` for your `Mail` builders

**Comment by nmeri17** [comment]
@AlessandroMinoccheri I used that rule to try and limit dependencies receivable by a class i.e.

```php
protected function restrictCoordinator () {

			return Rule::allClasses()
			
			->that(new Extend(ServiceCoordinator::class))

			->should(
				new DependsOnlyOnTheseNamespaces(...[
					ConditionalFactory::class, // We're treating it as a type of service in itself
					ControllerModule::class, // These are a service already. There's no need accessing them through another local proxy

					PayloadStorage::class, // there may be items we don't want to pass to the builder but to a service?

					BaseHttpRequest::class, UpdatefulService::class,

					UpdatelessService::class
				], // constructor arguments
				...[

					ModelfulPayload::class, ModellessPayload::class
				]) // action method arguments
			);
		}
```
I don't expect any descendant of ServiceCoordinator to import any of those classes. I've not tested it yet but that's the intended behavior

**Comment by AlessandroMinoccheri** [comment]
ok, so it seems ok that rule is for your purpose right?

**Comment by nmeri17** [comment]
> ok, so it seems ok that rule is for your purpose right?

Sorry, is this a typo? I don't understand your message

**Comment by AlessandroMinoccheri** [comment]
with the rule `DependsOnlyOnTheseNamespaces` you can achieve what you want I think, so what do you expect instead?
What behavior do you want in your `OnlyLoadedByHandler` class?
