### ISSUE TITLE
Excluding classes extending X reports parent as violation

### ISSUE THREAD

**Issue by nmeri17** [phparkitect/arkitect#319]
@AlessandroMinoccheri I used that rule to try and limit dependencies receivable by a class i.e.

```php
protected function restrictCoordinator () {

			return Rule::allClasses()
			
			->that(new Extend(ServiceCoordinator::class))

			->should(
				new DependsOnlyOnTheseNamespaces(...[
					ConditionalFactory::class, // We're treating it as a type of service in itself
					ControllerModule::class, // These are a service already. There's no need accessing them through another local proxy

					PayloadStorage::class, // there may be items we don't want to pass to the builder but to a service?

					BaseHttpRequest::class, UpdatefulService::class,

					UpdatelessService::class
				], // constructor arguments
				...[

					ModelfulPayload::class, ModellessPayload::class
				]) // action method arguments
			);
		}
```
I don't expect any descendant of ServiceCoordinator to import any of those classes. I've not tested it yet but that's the intended behavior. It's a different behavior to this:

> I only want Mail builders to be used by Task classes

_Originally posted by @nmeri17 in https://github.com/phparkitect/arkitect/issues/318#issuecomment-1340523160_
     
When I run the rules above, all classes extending ServiceCoordinator are reported as violations since ServiceCoordinator isn't on the list. Is this a bug or intended behaviour? I obviously expect ServiceCoordinator to be regarded as part of the rule set but don't want to include it on the list since ServiceCoordinators can't depend on each other

**Comment by AlessandroMinoccheri** [comment]
This rule that you have built means:
every class that extends `ServiceCoordinator ` can have only  these dependencies:
```
ConditionalFactory::class, ControllerModule::class, PayloadStorage::class, BaseHttpRequest::class, UpdatefulService::class,
UpdatelessService::class...
```
So `ServiceCoordinator ` is not included because it can't extend itself.
