### ISSUE TITLE
Passing FQCNs to expressions is not reliable

### ISSUE THREAD

**Issue by javaDeveloperKid** [phparkitect/arkitect#323]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Library Version | 0.3.5
| PHP version     | 8.0

#### Summary
Passing FQCNs to expressions is not reliable.

#### Current behavior
Passing FQCNs do expressions like (Not)Implements or (Not)Extends etc. will consider also FQCNs that **start with** the given FQCN. Example:
```php
namespace App\Interface;

interface Order {}
interface Orderable {}
```
now, the following arkitect rule will consider both Order and Orderable implementations:
```php
    $rules[] = Rule::allClasses()
        ->that(new Implement(Order::class))
        ->should(new ResideInOneOfTheseNamespaces('App\MyNamespace'))
        ->because('I said so');
```
This happens because the `str_starts_with` function will be used. When I use `new Implement` class and pass given interface then I expect **not to receive** errors about classes that do not implement this interface but implement an interface that has a very similar FQCN.

**Comment by fain182** [comment]
This is fixed in main branch now, you can test it if you want... will be released soon :slightly_smiling_face:

**Comment by AlessandroMinoccheri** [comment]
Released the new version with the fix!
