### ISSUE TITLE
Bug in `except` method with regex input

### ISSUE THREAD

**Issue by smortexa** [phparkitect/arkitect#329]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | yes
| Library Version | 0.3.9
| PHP version     | 8.1.8

#### Summary

After upgrading the library  to version `0.3.9` the following code doesn't work:
`->except('App\Providers\(Auth|Event|Route|Horizon)ServiceProvider')`
but this works:
`->except('App\Providers\AuthServiceProvider', 'App\Providers\EventServiceProvider')`

#### Current behavior

```php
App\Providers\AuthServiceProvider has 1 violations
  should extend Illuminate\Support\ServiceProvider because we use Laravel framework!

App\Providers\EventServiceProvider has 1 violations
  should extend Illuminate\Support\ServiceProvider because we use Laravel framework!

App\Providers\HorizonServiceProvider has 1 violations
  should extend Illuminate\Support\ServiceProvider because we use Laravel framework!

App\Providers\RouteServiceProvider has 1 violations
  should extend Illuminate\Support\ServiceProvider because we use Laravel framework!
```

#### How to reproduce

Use `providers` rule in https://github.com/smortexa/laravel-arkitect:
```php
Rule::allClasses()
            ->except('App\Providers\(Auth|Event|Route|Horizon)ServiceProvider')
            ->that(new ResideInOneOfTheseNamespaces('App\Providers'))
            ->should(new Extend('Illuminate\Support\ServiceProvider'))
            ->because('we use Laravel framework!');
```

#### Expected behavior

No violation report.

**Comment by AlessandroMinoccheri** [comment]
Hi @smortexa, in previous releases works fine your example?

**Comment by smortexa** [comment]
@AlessandroMinoccheri Yes. Until this MR: https://github.com/smortexa/laravel-arkitect/pull/15

**Comment by AlessandroMinoccheri** [comment]
@fain182 could it be related to the last work on regexp?

**Comment by fain182** [comment]
Yes, it could be.. I work on it

**Comment by fain182** [comment]
@smortexa actually the regex support was added by error... we support only shell wildcard ( `*` and` ?`).

With the new release we added an explicit error message for regex.
