### ISSUE TITLE
Add a configuration to skip PHPDoc Custom Tag detection

### ISSUE THREAD

**Issue by LuigiCardamone** [phparkitect/arkitect#336]
### Feature Request

Add a configuration to skip PHPDoc Custom Tag detection since in some projects annotation like `@JMS\Expose` cannot be easily removed. I think that skipping this check is not wrong since these annotations are not real dependencies. 

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

I will try to make a PR for this feature.

**Comment by AlessandroMinoccheri** [comment]
Closed by #337
