### ISSUE TITLE
Violations on typed arrays are not detected

### ISSUE THREAD

**Issue by LuigiCardamone** [phparkitect/arkitect#344]
### Bug Report

Violation on typed array are not detected. If I have an array of object with Type Foo, violations related to Foo are not detected.

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Library Version | 0.3.12

#### Summary

I have a failing test:

```php
public function test_it_handles_typed_arrays(): void
    {
        $code = <<< 'EOF'
<?php
namespace Domain\Foo;

use Domain\Bar;
use Application\MyDto;

class MyClass
{
    /**
     * @var array<int, MyDto>
     */
    private array $dtoList;

    /**
     * @param array<int, MyDto> $dtoList
     */
    public function __construct(Bar $bar, array $dtoList)
    {
        $this->dtoList = $dtoList;
    }

    /**
     * @return array<int, MyDto>
     */
    public function getList(): array
    {
        return $this->dtoList;
    }
}
EOF;

        /** @var FileParser $fp */
        $fp = FileParserFactory::createFileParser(TargetPhpVersion::create('7.1'));
        $fp->parse($code, 'relativePathName');
        $cd = $fp->getClassDescriptions();

        $violations = new Violations();

        $dependsOnTheseNamespaces = new DependsOnlyOnTheseNamespaces('Domain');
        $dependsOnTheseNamespaces->evaluate($cd[0], $violations, 'we want to add this rule for our software');

        $this->assertCount(3, $violations);
    }
```

Typed array may be defined using different format:
- `@var array<int, MyDto>`
- `@var MyDto[]`
- `@var list<MyDto>`

**Comment by LuigiCardamone** [comment]
@AlessandroMinoccheri do you have any idea on how we can do this? Since array definitions may be nested could make sense to search for some external library?

**Comment by AlessandroMinoccheri** [comment]
@LuigiCardamone I have an idea but would like to explore more possible solutions.
My idea is to create a RegEx inside `NameResolver.php` where we parse docComments to get array inner values.
At the moment our code creates this dependency:
`Domain\Foo\array<int, MyDto>`

So we must understand that the string contains an `array` type with types.

At the moment I have no other solutions but I am opened to other ways.

cc @micheleorselli

**Comment by LuigiCardamone** [comment]
If we want to cover all the cases, maybe we can give a look at this library: https://github.com/phpstan/phpdoc-parser .
This should cover also cases like `@var MyList<MyObject>`. Otherwise we can make a list of most relevant annotations for typed arrays and write some RegEx as @AlessandroMinoccheri is suggesting.

**Comment by AlessandroMinoccheri** [comment]
We are using already that library, we should understand how to work with it with this problem
Do you wanna try @LuigiCardamone ?

**Comment by LuigiCardamone** [comment]
@AlessandroMinoccheri with the PhpDocParser I can extract the inner types from a typed array but there is a problem. In `NameResolver.php` for each Node you store a single type `$node->type` but in the definition `array<int, MyDto>` I have 3 types:
- the main type that is `array`
- the type of the key that is `int`
- the type of the value that is `MyDto`

How can I handle this? The dirty solution is to `$node->type = 'MyDto'`. Other ideas?

**Comment by AlessandroMinoccheri** [comment]
@LuigiCardamone good point, we can also try to return `array<int, Application\MyDto>` and manage this new type in a specific part of the code splitting.

Returning only `MyDto` can save you from this situation `array<int, Application\MyDto>` but not from this: `array<Infrastructure\MyDto2, Application\MyDto>`

**Comment by LuigiCardamone** [comment]
@AlessandroMinoccheri if we assign `$node->type = 'array<int, Application\MyDto>'` in which part of the code we should decode `$node->type` into 3 dependencies? Can you indicate the involved class?

**Comment by AlessandroMinoccheri** [comment]
We can change the approach I think.
We can assign the type Application\MyDto only to the node.
It's difficult that we will have two objects.
What do you think. 
In this way we can supporto typed Array 
@LuigiCardamone

**Comment by AlessandroMinoccheri** [comment]
Can we consider this issue closed @LuigiCardamone ?

**Comment by LuigiCardamone** [comment]
@AlessandroMinoccheri yes, we can close this issue
