### ISSUE TITLE
regression with pattern validation

### ISSUE THREAD

**Issue by dbu** [phparkitect/arkitect#358]
### BC Break Report

adding rules for namespaces no longer works.

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | (https://github.com/phparkitect/arkitect/pull/352/files#r1105961189)

#### Summary

i just tried something with latest main and this breaks what worked before for us.

we add rules like this:

    addRules($config, 'Client', ['App\\Client\\SomeClient\\*', ...SPECIAL_RULES_NAMESPACES]);

it now complains that this is a regex.

    analyze class set /usr/src/app/src/Client

        0/1315 [>---------------------------]   0%'App\Client\SomeClient\*' is not a valid class or namespace pattern. Regex are not allowed, only * and ? wildcard.

when i comment out the check for valid pattern in the matches function, everything still works. is the pattern checker incorrect? or how should i separate namespaces?

#### Previous behavior

It accepted the pattern.

#### Current behavior

It rejects the pattern

#### How to reproduce

    addRules($config, 'Client', ['App\\Client\\SomeClient\\*']);

**Comment by fain182** [comment]
Thanks for reporting this! :slightly_smiling_face: 

I tried to reproduce your problem, but I can't...

Can you give me the implementation of the `addRules()` function?

**Comment by LuigiCardamone** [comment]
@fain182 we have the same problem.

we have namespace like this: `namespace Project\Module\F24\Exception;`

and the error in console is:
` 120/597 [=====>----------------------]  20%'Project\Module\F24\Exception' is not a valid class or namespace pattern. Regex are not allowed, only * and ? wildcard.`

I solved locally by allowing numbers in this regexp:
```
    public function isNotAValidPattern(string $pattern): bool
    {
        return 0 === preg_match('/^([A-Za-z]|\\\\|\*|\?)*$/', $pattern);
    }
```

If I put `A-Za-z0-9` everything works, can you confirm?

**Comment by dbu** [comment]
oh, i think thats it. sorry, when i anonymized the namespaces (as this is on a customer project), i destroyed the example. SomeClient actually has a number in it... I am pretty sure this is the problem.

does it make sense to do preg_match to check for valid pattern? php classes can have a lot more characters. maybe instead check for unescaped regular expression syntax and only complain then? see for example  https://www.php.net/manual/en/language.oop5.basic.php  (but i think thats outdated, you can even have emoji in class names: https://3v4l.org/HRuhP )

**Comment by fain182** [comment]
@LuigiCardamone thank you! 
I wrote the fix, we will merge it soon...

@dbu I am open to different strategies, what do you mean by "check for unescaped regular expression syntax" ?

**Comment by dbu** [comment]
> @dbu I am open to different strategies, what do you mean by "check for unescaped regular expression syntax" ?

sorry, the "unescaped" makes no sense. i was thinking that you could scan only for regex things like wildcard `.` ranges `[]` groups, `()` or character classes, but not limit namespaces to a letters and numbers, as moder PHP allows lots of unicode characters in class names and namespaces.

**Comment by dbu** [comment]
that said, our own code only has the number problem, so allowing the regex from https://www.php.net/manual/en/language.oop5.basic.php would solve the issue for us.

**Comment by fain182** [comment]
@dbu ook, i use that regex now, and should fix some other cases that I didn't thought of (like underscores).

I fear that with checking for regex instead of namespaces, we would have much more corner cases.
If the issue come back, we will change strategy :slightly_smiling_face:
