### ISSUE TITLE
"is not a valid class or namespace pattern" since 0.3.15

### ISSUE THREAD

**Issue by reindert-vetter** [phparkitect/arkitect#361]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     |  0.3.15

#### Summary

The analysis incorrectly indicates that the \App namespace is in use. That is correct, but in the previous version I could make an exception. I need that exception because I want to allow \App\Events and \App\Contract.

#### Previous behavior

I could make an exception.

#### Current behavior

The analysis ignores my exception
![image](https://user-images.githubusercontent.com/16726304/220596873-cff5a9ce-a7ef-47c4-8cd1-3938519ff77d.png)

#### How to reproduce

```php
return static function (Config $config): void {
    $modules = ClassSet::fromDir(__DIR__ . '/../modules');

    $rules = [];

    $rules[] = Rule::allClasses()
        ->that(new ResideInOneOfTheseNamespaces('Modules'))
        ->should(new NotDependsOnTheseNamespaces(...forbiddenModuleNamespaces()))
        ->because('we want to isolate our domain');

    $config
        ->add($modules, ...$rules);
};

function forbiddenModuleNamespaces(): array
{
    $forbidden = scandir('app');
    $forbidden = array_filter($forbidden, function (string $dir) {
        return !in_array($dir, ['Events', 'Contracts']);
    });
    return array_map(function (string $dir) {
        return 'App\\' . $dir;
    }, $forbidden);
}
```

Directory tree example:
- app/Actions
- app/Contracts
- app/Events
- app/Http
- app/Support
- app/Traits
- modules/Statistics/Config
- modules/Statistics/Enums
- modules/Statistics/Http

**Comment by fain182** [comment]
I suppose the problem is that you are passing `App/.` as a namespace, instead of `App/`.

**Comment by reindert-vetter** [comment]
Thanks! You're right. I'm filtering it out now:

```php
function forbiddenModuleNamespaces(): array
{
    $forbidden = scandir('app');
    $forbidden = array_filter($forbidden, function (string $dir) {
        return !in_array($dir, [
            '.',
            '..',
            'Events',
            'Contracts',
        ]);
    });
    return array_map(function (string $dir) {
        return 'App\\' . $dir;
    }, $forbidden);
}
```

**Comment by fain182** [comment]
Great! I’m happy to help :slightly_smiling_face:
