### ISSUE TITLE
Support OR in HaveNameMatching

### ISSUE THREAD

**Issue by fain182** [phparkitect/arkitect#362]
This discussion: https://github.com/smortexa/laravel-arkitect/issues/19 raise the problem to have a rule that can express "have a name matching X or Y".

It could be implemented by passing an array of pattern to the `HaveNameMatching` or maybe creating a new rule named `HaveNameMatchingOneOf` or something similar.

**Comment by AlessandroMinoccheri** [comment]
Do you mean something like this @fain182?

```
$rules = Rule::allClasses()
    ->that(new ResideInOneOfTheseNamespaces('App\Service'))
    ->should(new HaveNameMatching(['*Service', *Handler']))
    ->because('we want uniform naming for services');
```

**Comment by fain182** [comment]
Exactly

**Comment by AlessandroMinoccheri** [comment]
This is a Breaking Change, isn't it @fain182?
If we introduce this new behavior, can be useful for other rules?

**Comment by fain182** [comment]
A lot of other rules could have similar needs like `Implement` or `Extend`, but maybe a more explicit alternative is to create a `HaveNameMatchingOneOf` that would be similar to `ResideInOneOfTheseNamespaces` (or `MatchOneOfTheseNames` ? ).

**Comment by AlessandroMinoccheri** [comment]
Yes, I was thinking the same thing.
We are adding a lot of rules to maintain also, but in this way we can support different behaviours without BC.
What do you think @micheleorselli ?

**Comment by micheleorselli** [comment]
I do think the explicit alternative is the way (tm), even if it means to mantain more rules :-)

**Comment by fain182** [comment]
Thank you for the feedback @smortexa, can you give me some examples of other broken rules so we can understand better your needs?

**Comment by smortexa** [comment]
https://github.com/smortexa/laravel-arkitect/blob/a36b1bc6da1360b460bb28d45e4c0249975b7810/src/Rules/Naming/ExceptionsNaming.php#L24

https://github.com/smortexa/laravel-arkitect/blob/a36b1bc6da1360b460bb28d45e4c0249975b7810/src/Rules/Extending/ModelsExtending.php#L23

https://github.com/smortexa/laravel-arkitect/blob/a36b1bc6da1360b460bb28d45e4c0249975b7810/src/Rules/Naming/ResourcesNaming.php#L24

https://github.com/smortexa/laravel-arkitect/blob/a36b1bc6da1360b460bb28d45e4c0249975b7810/src/Rules/Extending/ProvidersExtending.php#L23

**Comment by szepeviktor** [comment]
What may I do to move towards a solution?

**Comment by fain182** [comment]
I think the next step is to create the `MatchOneOfTheseNames` rule that works like `HaveNameMatching` but takes an array as argument.

Thanks for your contribution :slightly_smiling_face:

**Comment by szepeviktor** [comment]
Thank you @fain182! Could you release it please?

**Comment by AlessandroMinoccheri** [comment]
We will release it today @szepeviktor
