### ISSUE TITLE
Optional Class Property Dependencies not detected

### ISSUE THREAD

**Issue by fp-cfr** [phparkitect/arkitect#371]
### Bug Report

|    Q            |   A
|---------------- | ------
| Library Version | 0.3.19 
| PHP version     | 8.1

#### Current behavior

When I use optional properties, the dependencies of the properties are not detected.

#### How to reproduce

In FileVisitorTest::test_it_parse_typed_property() make NotBlank optional:
`public ?NotBlank $foo;` 
https://github.com/phparkitect/arkitect/blob/9e5c5a17517d131691c3333ce13dab8a73e817cd/tests/Unit/Analyzer/FileVisitorTest.php#L538

#### Expected behavior

Optional Property Dependencies should be detected correctly.

**Comment by fp-cfr** [comment]
Thanks @AlessandroMinoccheri for the quick fix.
Optional Class Property Dependencies are recognized correctly.

In my project we work a lot with constructor property promotion. in this case your fix don't work 😢 

**How to reproduce**

`public function __construct(public ?NotBlank $foo){}`

**Comment by AlessandroMinoccheri** [comment]
Hi @fp-cfr , can you please open a new issue for the new problem?
Thanks a lot 😊
