### ISSUE TITLE
Optional Constructor Promoted Property Dependencies not detected

### ISSUE THREAD

**Issue by fp-cfr** [phparkitect/arkitect#373]
### Bug Report

|    Q            |   A
|---------------- | ------
| Library Version | 0.3.20 
| PHP version     | 8.1

#### Current behavior

When I use optional properties promoted in the constructor, the dependencies of the properties are not detected.

#### How to reproduce

Similar to https://github.com/phparkitect/arkitect/issues/371#issuecomment-1484618340

`public function __construct(public ?NotBlank $foo){}`

#### Expected behavior

Optional Constructor Promoted Property Dependencies should be detected correctly.

**Comment by AlessandroMinoccheri** [comment]
Thanks @fp-cfr 
We will release in next hour the new minor version with the fix of this issue!

**Comment by fp-cfr** [comment]
You are amazing! Thank you so much 👍
