### ISSUE TITLE
Nullable native fields are reported as external dependencies

### ISSUE THREAD

**Issue by azambon** [phparkitect/arkitect#376]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Library Version | 0.3.21 
| PHP version     | 8.2.4

#### Summary

Upon updating from version 0.3.20 to 0.3.21, we began receiving violations caused by nullable native types being regarded as external dependencies.

#### How to reproduce

Configuration:
![Schermata del 2023-03-31 10-09-37](https://user-images.githubusercontent.com/2920227/229063874-8f2c9e9c-fb4b-4ff4-86f4-dec3b0e4b823.png)

Code:
![Schermata del 2023-03-31 10-13-44](https://user-images.githubusercontent.com/2920227/229064285-bc1ad814-5d23-43c7-aba5-46c9c89d8493.png)

#### Expected behavior

No violations should be reported on that class.

#### Current behavior

![Schermata del 2023-03-31 10-08-47](https://user-images.githubusercontent.com/2920227/229064047-f6b22a1c-4947-4783-883f-69b257dfee9c.png)

**Comment by AlessandroMinoccheri** [comment]
Hi @azambon, I understood the problem, I hope to solve it as soon as possible.
Thanks for reporting it.
