### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by nelsonkopliku** [phparkitect/arkitect#94]
Since I am new to the project, I'd like to understand more about the choices made.
The following points emerged while digging the code and debugging the execution.
Didn't go further than this so far.

Would be nice to discuss on these for me to better understand 😇 

`bin-stub/phparkitect`

```
foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('PHPARKITECT_COMPOSER_INSTALL', $file);

        break;
    }
}

unset($file);

if (!defined('PHPARKITECT_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}
```
Why are we looking in different locations for an autoloader?
I get the second part about checking for dependencies being installed 🙂 

---

`Arkitect\Rules\RuleChecker::$rules` seems to not being used on instanciated object.

in `Arkitect\Rules\RuleChecker::build(ClassSet $classSet, ArchRule ...$rules)` $rules are passed to the `$fileParser` in order to be evaluated when a class has been analyzed by `php-parser`, but never really used in `Arkitect\Rules\RuleChecker` instance.

Ise there a plan to use that property internally in `RuleChecker`?

---

`\Arkitect\Analyzer\FileVisitor::enterNode:(26,27)` seems to be adding the same dependency twice via the `ClassDescriptionBuilder`

```
foreach ($node->implements as $interface) {
    $this->classDescriptionBuilder
         ->addInterface($interface->toString(), $interface->getLine())
         ->addDependency(new ClassDependency($interface->toCodeString(), $interface->getLine()));
}
```

See `ClassDescriptionBuilder::addInterface` and `ClassDescriptionBuilder::addDependency` implementations
```
class ClassDescriptionBuilder
{
    ...
    public function addInterface(string $FQCN, int $line): self
    {
        $this->addDependency(new ClassDependency($FQCN, $line));
        $this->interfaces[] = FullyQualifiedClassName::fromString($FQCN);

        return $this;
    }

    public function addDependency(ClassDependency $cd): self
    {
        $this->classDependencies[] = $cd;

        return $this;
    }
    ...
}
```
Is this intended?

---

Context:
**config** `tests/E2E/fixtures/configMvc.php`
**class being analyzed** `App\Controller\CatalogController`

In `ClassDescriptionBuilder::get` the property `$this->filePath` is empty
```
public function get(): ClassDescription
{
    $cd = new ClassDescription($this->FQCN, $this->classDependencies, $this->interfaces);
    $cd->setFullPath($this->filePath);

    return $cd;
}
```

And then it gets set like this `$classDescription->setFullPath($currentlyAnalyzedFile->toString());` in `RuleChecker:51`.
In this case the value gets overridden by `Controller`.

Is `Controller` a `fullPath`?

---

```
interface Expression
{
    /**
     * Returns a human readable description of the expression
     * $theClass can be used to add contextual information.
     */
    public function describe(ClassDescription $theClass): Description;

    /**
     * Evaluates the expression for the class passed as parameter.
     * It should adds violations if rule is violated.
     */
    public function evaluate(ClassDescription $theClass, Violations $violations): void;
}
```
Not completely sure about the interface of the `evaluate` method which is `void`.
This means a side effect in the method that modifies the violations.

Would an interface like `public function evaluate(ClassDescription $theClass): Violations;` be as effective and safer from side effect point of view?

Similar thoughts for

```
interface ArchRule
{
    public function check(ClassDescription $classDescription, Violations $violations): void;
}
```

**Comment by AlessandroMinoccheri** [comment]
@nelsonkopliku can we close this issue or do you need more answers or discussion about something?

**Comment by nelsonkopliku** [comment]
You can close this issue.
The answers should be enough for now. Thanks!
