### ISSUE TITLE
Add verbose mode

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [phparkitect/arkitect#98]
It could be useful to add a verbose mode because sometimes is necessary to see which file phparkitect is parsing and if there are some problems.

**Comment by micheleorselli** [comment]
I think we could provide a couple of ways to display progress
- a compact mode, where a progress bar from 0 to 100% is showed
- a verbose mode, where every analysed file is listed

Will this be enough as a first step?

**Comment by AlessandroMinoccheri** [comment]
Yes, each way can be a different pull request, what do you think?
